parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: pollina
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 72b1ba299a8d1579be37764068b835e6c545a039
    database_path: null
